version: '3.6'
services:
  database:
    network_mode: host
    build: ./database
    volumes:
    - ./database/patches:/docker-entrypoint-initdb.d
    environment:
    - MYSQL_USER=mysql
    - MYSQL_PASSWORD=vagrant
    - MYSQL_ROOT_PASSWORD=vagrant
